# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-17 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_app', '0002_auto_20161116_1011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '\u0422\u044d\u0433', 'verbose_name_plural': '\u0422\u044d\u0433\u0438'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(upload_to='static/images/avatars'),
        ),
    ]
