# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-17 19:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_app', '0003_auto_20161117_1833'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': '\u041f\u0440\u043e\u0444\u0438\u043b\u044c', 'verbose_name_plural': '\u041f\u0440\u043e\u0444\u0438\u043b\u0438'},
        ),
        migrations.AddField(
            model_name='answer',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
