# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-17 11:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ask_app', '0007_auto_20161118_1852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answerlike',
            options={'verbose_name': '\u041b\u0430\u0439\u043a \u043e\u0442\u0432\u0435\u0442\u0430', 'verbose_name_plural': '\u041b\u0430\u0439\u043a\u0438 \u043e\u0442\u0432\u0435\u0442\u043e\u0432'},
        ),
        migrations.AlterModelOptions(
            name='questionlike',
            options={'verbose_name': '\u041b\u0430\u0439\u043a \u0432\u043e\u043f\u0440\u043e\u0441\u0430', 'verbose_name_plural': '\u041b\u0430\u0439\u043a\u0438 \u0432\u043e\u043f\u0440\u043e\u0441\u043e\u0432'},
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='user',
            new_name='author',
        ),
        migrations.AddField(
            model_name='question',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='answer',
            name='correct',
            field=models.BooleanField(default=False, verbose_name='\u041f\u0440\u0430\u0432\u0438\u043b\u044c\u043d\u044b\u0439 \u043e\u0442\u0432\u0435\u0442'),
        ),
        migrations.AlterField(
            model_name='answerlike',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ask_app.Answer', verbose_name='\u041e\u0442\u0432\u0435\u0442'),
        ),
        migrations.AlterField(
            model_name='answerlike',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u0410\u0432\u0442\u043e\u0440'),
        ),
        migrations.AlterField(
            model_name='answerlike',
            name='value',
            field=models.SmallIntegerField(default=0, verbose_name='\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(upload_to='images/avatars', verbose_name='\u0410\u0432\u0430\u0442\u0430\u0440'),
        ),
        migrations.AlterField(
            model_name='questionlike',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u0410\u0432\u0442\u043e\u0440'),
        ),
        migrations.AlterField(
            model_name='questionlike',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ask_app.Question', verbose_name='\u0412\u043e\u043f\u0440\u043e\u0441'),
        ),
        migrations.AlterField(
            model_name='questionlike',
            name='value',
            field=models.SmallIntegerField(default=0, verbose_name='\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=50, unique=True, verbose_name='\u0422\u044d\u0433'),
        ),
        migrations.AlterUniqueTogether(
            name='answerlike',
            unique_together=set([('author', 'answer')]),
        ),
        migrations.AlterUniqueTogether(
            name='questionlike',
            unique_together=set([('author', 'question')]),
        ),
    ]
