# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-17 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask_app', '0008_auto_20161217_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='likes',
        ),
    ]
