# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-17 11:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask_app', '0009_remove_question_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='author',
            new_name='user',
        ),
    ]
