# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-17 12:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask_app', '0010_auto_20161217_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='user',
            new_name='author',
        ),
    ]
