# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-17 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_app', '0011_auto_20161217_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
